#! /bin/sh

# Run pkgsync. It inhibit shutdown or reboot if systemd-inhibit is installed.

export PATH=/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin

if [ -x /usr/local/sbin/pkgsync ]; then
   if [ -x /bin/systemd-inhibit ]; then
      /bin/systemd-inhibit --what="idle:sleep:shutdown:handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch" --why="Doing pkgsync" bash /usr/local/sbin/pkgsync
   else
      bash /usr/local/sbin/pkgsync
   fi
fi
