#!/bin/bash
#
# nombre              : apt-list-expired-keys
# descripción         : Listar claves públicas de repositorios expiradas
# autor               : Esteban M. Navas Martín
# fecha creación      : 10032020
# última modificación : 10032020
# uso                 : apt-list-expired-keys
# instalación         : Guardar en  /usr/local/sbin/

#
# Copyright 2020, Esteban M. Navas Martín <algodelinux@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
#

APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 LC_ALL=C apt-key list |grep -E pub.*expired -A 1
