#!/bin/bash
# backup-repositories - Realiza un backup de los repositorios
# almacenados en /etc/apt/sources.list y los alojados en el
# directorio /etc/apt/sources.list.d/ en el directorio definido
# en la variable $BACKUP_DIR
# 2018-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

BACKUP_DIR="/var/backups"

[ -d $BACKUP_DIR ] || mkdir $BACKUP_DIR

# Realizamos un backup de los ficheros de fuentes
tar cfzP $BACKUP_DIR/sources.list.tar.gz /etc/apt/sources.list /etc/apt/sources.list.d

