#!/bin/bash
# clean-pkgsync-files - Elimina de las listas de paquetes de pkgsync aquellos ficheros que no se encuentran en los repositorios
# 2019-2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

:>/var/log/pkgsync/removedfromlists.log

for fichero in $(find /etc/pkgsync -type f -not -name "*.all" -not -name "*.bak*" -not -name "musthave.????????"); do
    echo "Checking $fichero"
    while read paquete; do
       echo "Checking $fichero: $paquete"

       LC_ALL=C apt-cache --quiet=0 policy $paquete 2>&1 | tr -d " " | grep -e 'Candidate:(none)' -e 'N:Unabletolocatepackage' 2>&1>/dev/null

       if [ $? -eq 0 ]; then
          echo "Removed package $paquete from file $fichero"
          echo "Removed package $paquete from file $fichero" >> /var/log/pkgsync/removedfromlists.log

          sed -i "/$paquete/ d" $fichero
       fi
    done < $fichero
 done
 echo "See /var/log/pkgsync/removedfromlists.log"
