#!/bin/bash
# clean-pkgsync-files - Elimina de las listas de paquetes de pkgsync aquellos ficheros que no se encuentran en los repositorios
# 2019-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

:>/var/log/pkgsync/removefromlists.log

for fichero in $(find /etc/pkgsync -type f -not -name "*.all" -not -name "*.bak*" -not -name "musthave.[[:digit:]]*"); do
    if [ -s "$fichero" ]; then
       for linea in $(sed '/^[[:blank:]]*#/d;s/#.*//;' $fichero); do
           paquete=$(echo $linea | cut -f1 -d" ")
           echo "Checking $fichero: $paquete"

           LC_ALL=C apt-cache --quiet=0 policy $paquete 2>&1 | tr -d " " | grep -e 'Candidate:(none)' -e 'N:Unabletolocatepackage' 2>&1>/dev/null

           if [ $? -eq 0 ]; then
              echo "Removed package $paquete from file $fichero"
              echo "Removed package $paquete from file $fichero" >> /var/log/pkgsync/removedfromlists.log

              sed -i "/$paquete/ d" $fichero
           fi
       done
    fi
done
echo "See /var/log/pkgsync/removedfromlists.log"

