#!/bin/bash
# disable-pkgsync-terminal - Deshabilita el inicio automático del usuario pkgsync en el terminal 12
# 2013-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

if [ -f /lib/systemd/system/getty@tty12.service ]; then
   systemctl stop getty@tty12.service
   systemctl disable getty@tty12.service
   systemctl daemon-reload
fi

