#!/bin/bash
# enable-non-failed-repositories - Habilita repositorios deshabilitados en
# /etc/apt/sources.list.d/ quitando a los ficheros.list la extensión .disabled
# pero manteniendo deshabilitados aquellos que fallan.
# 2013-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

for file in /etc/apt/sources.list.d/*.disabled; do
    [ -f $file ] && mv -f "$file" "${file%%.disabled}"
done

/usr/local/sbin/disable-failed-repositories
