#!/bin/bash
# get-package-dependencies - Muestra las dependencias de un paquete introducido como parámetro
# Sintaxix get-package-dependencies package-name
# 2013-2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

if [ -n "$1" ]; then
   LC_ALL=C apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends $1 2>/dev/null |  sed 's/^ *//; s/^|Depends: //; s/Depends: //; /<.*>/d; 1d'|sort -u
fi
