#!/bin/bash
# -------------------------------------------------------------------------------------------
# script: install-last-available-kernels
# Author:  Esteban M. Navas Martín
# Date:    09-02-2024
# Ver:     07-02-2025
#
# Purpose: Script para instalar los n últimos kernels

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

if [ ! -z "$1" ]; then
    numkernels="$1"
    AVAILABLE_KERNELS=$(apt-cache search linux-image-$(uname -r | cut -d'.' -f1,2) | sort -V | grep generic | tail -$numkernels | awk '{print $1}' | sed 's/linux-image-//')
else
    echo -e "${RED}Error: Debe especificar el número de kernels a instalar${NC}"
    echo -e "${GREEN}Sintaxis: $0 numero-de-kernels${NC}"
    exit 1
fi

for KERNEL_VERSION in $AVAILABLE_KERNELS; do
   for PACKAGE_NAME in linux-image linux-headers linux-modules linux-modules-extra; do
       FULLPACKAGENAME="$PACKAGE_NAME-$KERNEL_VERSION"
       if ! dpkg -l | grep -E "^ii\s+$FULLPACKAGENAME" > /dev/null 2>&1; then
          apt-get -y install $FULLPACKAGENAME
       fi
   done
done
