#!/bin/bash
# limpiapaquetes - Hace limpieza purgando paquetes desinstalados y limpia la cache de apt
#
# 2013-2025 Esteban M. Navas Martín
#

wait_while_locked () {
   [ -x /usr/local/sbin/wait_for_apt_or_dpkg ] && timeout $TIMEOUT_FOR_DPKG_OR_APT /usr/local/sbin/wait_for_apt_or_dpkg
}

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

TIMEOUT_FOR_DPKG_OR_APT="3m"

wait_while_locked; apt-get -fy install &&
wait_while_locked; dpkg --configure -a &&
wait_while_locked; apt-get -y remove --purge $(dpkg -l| grep -E '^(rc|ic)' | awk '{print $2}') &&
wait_while_locked; apt-get -y clean
[ $(which flatpak) ] && flatpak uninstall --unused -y
[ $(which snap) ] && LANG=C snap list --all | awk '/disabled/{print $1, $3}' |
  while read snapname revision; do
     snap remove "$snapname" --revision="$revision"
  done
