#!/bin/bash
# list-backup-repositories - Muestra un listado de los backups de los repositorios
# alojados en el directorio /etc/apt/ con extensión .save o extensión .orig
# 2013-2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

find /etc/apt/ -type f -iregex '.*\.\(save\|orig\)$'

