#!/bin/bash
# list-diabled-repositories - Muestra un listado de los ficheros de los repositorios
# alojados en el directorio /etc/apt/ deshabilitados con extensión .disabled
# 2013-2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

find /etc/apt/ -type f -iregex '.*\.disabled$'

