#!/bin/bash
# remove-failed-repositories - Elimina de /etc/apt/sources.list.d/ los repositorios que fallan
# 2013-2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#


# Buscamos los repositorios que fallan
LC_ALL=C apt-get update 2>&1 | grep '^Err:' | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%-]*" > /tmp/failedrepositories

# Eliminamos los repositorios que fallan de /etc/apt/sources.list.d
while read repository; do
 find /etc/apt/sources.list.d/ -iname "*.list" -exec grep -H "$repository" {} \; | cut -f1 -d":"

done </tmp/failedrepositories

