#!/bin/bash
# list-backup-repositories - Lista el contenido del fichero
# /var/backups/sources.list.tar.gz que almacena el backup
# de los repositorios de la máquina
# 2018-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.

BACKUP_DIR="/var/backups"

[ -d $BACKUP_DIR ] || mkdir $BACKUP_DIR

# Listamos el contenido del fichero de backup de los ficheros de fuentes
[ -f $BACKUP_DIR/sources.list.tar.gz ] && tar tvf $BACKUP_DIR/sources.list.tar.gz

