#!/bin/bash
#
# Elimina del fichero /etc/pkgsync/musthave los paquetes listados en los ficheros alojados en
# /etc/pkgsync/musthave.d/ junto con sus dependencias.
#
# 2013-2018 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

get-package-dependencies () {
   if [ -n "$1" ]; then
      LC_ALL=C apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends $1 2>/dev/null |  sed 's/^ *//; s/^|Depends: //; s/^Depends: //; /<.*>/d;' | sort -u
   fi
}

[ -f /etc/pkgsync/musthave ] && cp /etc/pkgsync/musthave /etc/pkgsync/musthave.$(date +"%Y%m%d")

for file in $(ls /etc/pkgsync/musthave.d/); do
    for package in $(cat /etc/pkgsync/musthave.d/$file); do
        echo "Borrando paquete $package del fichero /etc/pkgsync/musthave"
        sed -i "/$package/d" /etc/pkgsync/musthave
        get-package-dependencies $package > /tmp/dependencies
        echo "Borrando dependencias del paquete $package del fichero /etc/pkgsync/musthave"
        cat /tmp/dependencies
        comm -23 /etc/pkgsync/musthave /tmp/dependencies > /tmp/musthave
        mv /tmp/musthave /etc/pkgsync/musthave
    done
done

