#!/bin/bash
#
# Elimina del fichero /etc/pkgsync/musthave los paquetes listados en los ficheros alojados en
# /etc/pkgsync/musthave.d/ junto con sus dependencias.
#
# 2013-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

get-package-dependencies () {
   if [ -n "$1" ]; then
      LC_ALL=C apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends $1 2>/dev/null |  sed 's/^ *//; s/^|Depends: //; s/^Depends: //; /<.*>/d;' | sort -u
   fi
}

[ -f /etc/pkgsync/musthave ] && cp /etc/pkgsync/musthave /etc/pkgsync/musthave.$(date +"%Y%m%d")
[ -f /var/log/pkgsync/musthave-minimize.log ] && cp /var/log/pkgsync/musthave-minimize.log /var/log/pkgsync/musthave-minimize.log.$(date +"%Y%m%d")

for file in $(find /etc/pkgsync/ -path "*musthave.d/*"); do
    for line in $(sed '/^[[:blank:]]*#/d;s/#.*//;' $file); do
        package=$(echo $line | cut -f1 -d" ")

        grep $package /etc/pkgsync/musthave

        if [ $? -eq 0 ]; then
           echo "Borrando paquete $package del fichero /etc/pkgsync/musthave" | tee -a /var/log/pkgsync/musthave-minimize.log
           sed -i "/$package/d" /etc/pkgsync/musthave
           get-package-dependencies $package > /tmp/dependencies
           echo "Borrando dependencias del paquete $package del fichero /etc/pkgsync/musthave" | tee -a /var/log/pkgsync/musthave-minimize.log
           cat /tmp/dependencies
           comm -23 /etc/pkgsync/musthave /tmp/dependencies > /tmp/musthave
           mv /tmp/musthave /etc/pkgsync/musthave
        fi
    done
done

