#!/bin/bash
# remove-all-repositories - Elimina los los repositorios
# alojados en el directorio /etc/apt/sources.list.d 
# 2013-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

find /etc/apt/sources.list.d/ -type f -exec rm -f {} \;

