#!/bin/bash
# remove-backup-repositories - Elimina el fichero de backup de los repositorios
# alojado en el directorio /var/backups
# 2018-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if (( $EUID != 0 )); then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

BACKUP_DIR="/var/backups"

# Borramos el backup de los ficheros de fuentes
[ -f $BACKUP_DIR/sources.list.tar.gz ] && rm -f $BACKUP_DIR/sources.list.tar.gz
