#!/bin/bash
# remove-backup-repositories - Elimina el fichero de backup de los repositorios
# alojado en el directorio /var/backups
# 2018-2022 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

BACKUP_DIR="/var/backups"

# Borramos el backup de los ficheros de fuentes
[ -f $BACKUP_DIR/sources.list.tar.gz ] && rm -f $BACKUP_DIR/sources.list.tar.gz
