#! /bin/sh -e

if [ -f /etc/cron.d/pkgsync ]; then
	rm -f /etc/cron.d/pkgsync
fi

[ "`id -u pkgsync &>/dev/null`" ] || adduser --system --shell /bin/bash --home /var/home/pkgsync pkgsync

if [ -f /lib/systemd/system/getty@tty12.service ]; then
   systemctl start getty@tty12.service
   systemctl enable getty@tty12.service
   systemctl daemon-reload
fi

sed -i '/pkgsync.*/d' /etc/sudoers
